package com.redhat.coolstore

ruleflow-group "pricing-rules"
dialect "mvel"
no-loop true

rule
when
	$sc : com.redhat.coolstore.ShoppingCart( )
	$cartItemTotal : Double( ) from accumulate ( $sci : ShoppingCartItem( shoppingCart == $sc ),
		 sum($sci.price * $sci.quantity))
	$cartItemPromoSavings : Double( ) from accumulate ( $sci : ShoppingCartItem( shoppingCart == $sc ),
		 sum($sci.promoSavings * $sci.quantity))
then
	$sc.setCartItemTotal( $cartItemTotal );
	$sc.setCartItemPromoSavings( $cartItemPromoSavings * -1 );
	update( $sc );
