package com.redhat.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Shopping Cart Item")
public class ShoppingCartItem  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Price")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Double price;
    
    @org.kie.api.definition.type.Label(value = "Product")
    @org.kie.api.definition.type.Position(value = 3)
    private com.redhat.coolstore.Product product;
    
    @org.kie.api.definition.type.Label(value = "Promotional Savings")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Double promoSavings;
    
    @org.kie.api.definition.type.Label(value = "Quantity")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer quantity;

    public ShoppingCartItem() {
    }

    public ShoppingCartItem(java.lang.Double price, java.lang.Integer quantity, java.lang.Double promoSavings, com.redhat.coolstore.Product product) {
        this.price = price;
        this.quantity = quantity;
        this.promoSavings = promoSavings;
        this.product = product;
    }


    
    public java.lang.Double getPrice() {
        return this.price;
    }

    public void setPrice(  java.lang.Double price ) {
        this.price = price;
    }
    
    public com.redhat.coolstore.Product getProduct() {
        return this.product;
    }

    public void setProduct(  com.redhat.coolstore.Product product ) {
        this.product = product;
    }
    
    public java.lang.Double getPromoSavings() {
        return this.promoSavings;
    }

    public void setPromoSavings(  java.lang.Double promoSavings ) {
        this.promoSavings = promoSavings;
    }
    
    public java.lang.Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(  java.lang.Integer quantity ) {
        this.quantity = quantity;
    }
}